
" disable vi compatibility
set nocompatible

" enable line numbering
set number

" temporary disable file type detection
filetype off

" Python
au BufNewFile,BufRead *.py
  \ set tabstop=4       |
  \ set softtabstop=4   |
  \ set shiftwidth=4    |
  \ set expandtab       |
  \ set autoindent      |
  \ set textwidth=119   |
  \ set fileformat=unix |

" HTML/CSS/JS
au BufNewFile,BufRead *.html, *.css, *.js
  \ set tabstop=4       |
  \ set softtabstop=4   |
  \ set shiftwidth=4    |
  \ set expandtab       |
  \ set autoindent      |
  \ set textwidth=119   |
  \ set fileformat=unix |

" enable file type detection
filetype plugin indent on

