# added by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
#setopt nomatch
#unsetopt appendhistory autocd beep extendedglob notify
bindkey -v

# functions
fpath=($HOME/.zsh/functions $fpath)

# added by compinstall
zstyle :compinstall filename '/home/sander/.zshrc'
autoload -Uz compinit
compinit

KEYTIMEOUT=1

# plugins
source $HOME/.zsh/plugins/base16-default-dark.sh
source $HOME/.zsh/plugins/specialkeys.plugin.zsh
source $HOME/.zsh/plugins/python.plugin.zsh
source $HOME/.zsh/plugins/virtualenv.plugin.zsh
source $HOME/.zsh/plugins/virtualenvwrapper.plugin.zsh
source $HOME/.zsh/plugins/git.plugin.zsh
source $HOME/.zsh/plugins/docker-compose.plugin.zsh
